name: Windows RDP via Ngrok (Sử dụng Secret - Đã sửa đường dẫn Ngrok)

on: workflow_dispatch # Chạy thủ công

jobs:
  build:
    runs-on: windows-latest # Chạy trên máy ảo Windows
    timeout-minutes: 9999 # Giữ chạy lâu nhất có thể (trong giới hạn của GitHub)

    steps:
    # Bước 1: Tải Ngrok (Giải nén trực tiếp vào thư mục hiện tại)
    - name: Tải Ngrok
      shell: powershell
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath . # Ngrok.exe sẽ ở thư mục hiện tại
        Write-Host "✅ Đã tải và giải nén Ngrok."

    # Bước 2: Xác thực Ngrok (Sử dụng đường dẫn đúng)
    - name: Kết nối tài khoản Ngrok (Dùng Secret)
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      shell: powershell
      run: |
        if (-not $Env:NGROK_AUTH_TOKEN) {
            Write-Error "Lỗi: Secret 'NGROK_AUTH_TOKEN' chưa được đặt trong cài đặt kho lưu trữ!"
            exit 1
        }
        # Đường dẫn đúng là .\ngrok.exe
        .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        Write-Host "✅ Đã cấu hình Ngrok Authtoken từ Secret."

    # Bước 3: Kích hoạt RDP trên Windows
    - name: Kích hoạt truy cập Remote Desktop (RDP)
      shell: powershell
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Write-Host "✅ Đã kích hoạt RDP và mở Firewall."

    # Bước 4: Tạo người dùng và đặt mật khẩu mạnh
    - name: Tạo người dùng RDP và đặt mật khẩu
      shell: powershell
      run: |
        $userName = "havpc01"
        # --- !!! QUAN TRỌNG: THAY ĐỔI MẬT KHẨU NÀY !!! ---
        $password = "HavpcRDP@2025!" # Thay bằng mật khẩu mạnh của bạn
        # -------------------------------------------------
        Write-Host "INFO: Đang tạo người dùng '$userName' với mật khẩu đã đặt."
        $secPassword = ConvertTo-SecureString $password -AsPlainText -Force
        try {
            New-LocalUser -Name $userName -Password $secPassword -FullName "$userName (GitHub Actions)" -Description "Temp RDP User" -ErrorAction Stop
        } catch {
             Write-Error "Lỗi khi tạo người dùng '$userName': $_"
             Write-Warning "Thử đặt lại mật khẩu cho người dùng '$userName' đã tồn tại..."
             try { Set-LocalUser -Name $userName -Password $secPassword -ErrorAction Stop; Write-Host "Đã đặt lại mật khẩu." } catch { Write-Error "Lỗi khi đặt lại mật khẩu: $_"; exit 1 }
        }
        try { Add-LocalGroupMember -Group "Remote Desktop Users" -Member $userName -ErrorAction Stop } catch { if ($_.Exception.Message -like "*already a member*") { Write-Warning "'$userName' đã là thành viên RDP." } else { Write-Error "Lỗi thêm vào nhóm RDP: $_"; exit 1 } }
        try { Add-LocalGroupMember -Group "Administrators" -Member $userName -ErrorAction Stop; Write-Host "Đã thêm '$userName' vào nhóm 'Administrators'." } catch { if ($_.Exception.Message -like "*already a member*") { Write-Warning "'$userName' đã là Admin." } else { Write-Warning "Lỗi thêm vào Admin: $_" } }
        Write-Host "--------------------------------------------------" -ForegroundColor Green
        Write-Host "✅ Đã tạo/cập nhật người dùng RDP!" -ForegroundColor Green
        Write-Host "   👤 Username: $userName" -ForegroundColor Green
        Write-Host "   🔑 Password: $password" -ForegroundColor Green
        Write-Host "--------------------------------------------------" -ForegroundColor Green

    # Bước 5: Khởi động Ngrok Tunnel trong nền (Sử dụng đường dẫn đúng)
    - name: Tạo Ngrok Tunnel cho RDP (Cổng 3389)
      shell: powershell
      run: |
        Write-Host "Đang khởi động Ngrok tunnel cho cổng 3389 trong nền..."
        $ngrokLogPath = Join-Path -Path $env:RUNNER_TEMP -ChildPath "ngrok.log"
        # Đường dẫn đúng là .\ngrok.exe
        Start-Process powershell -ArgumentList "-NoExit", "-Command", "`".\ngrok.exe tcp 3389 --log '$ngrokLogPath'`""
        Write-Host "INFO: Ngrok đang chạy nền. Log tại: $ngrokLogPath"

    # Bước 6: Lấy và hiển thị URL Ngrok (với kiểm tra và tăng thời gian chờ)
    - name: Lấy và hiển thị địa chỉ kết nối Ngrok
      shell: powershell
      run: |
        $maxAttempts = 5
        $waitTime = 15
        for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
            Write-Host "⏳ Lần thử $attempt/$maxAttempts: Chờ $waitTime giây..."
            Start-Sleep -Seconds $waitTime
            Write-Host "⏳ Kiểm tra tiến trình Ngrok..."
            $ngrokProcess = Get-Process ngrok -ErrorAction SilentlyContinue
            if (-not $ngrokProcess) { Write-Warning "❌ Lỗi: Tiến trình ngrok.exe không chạy!"; continue }
            Write-Host "✅ Ngrok đang chạy (PID: $($ngrokProcess.Id)). Lấy URL API..."
            try {
                $tunnels = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels" -TimeoutSec 10 -ErrorAction Stop
                $tcpTunnel = $tunnels.tunnels | Where-Object {$_.proto -eq 'tcp'} | Select-Object -First 1
                if ($tcpTunnel) {
                    Write-Host "--------------------------------------------------" -ForegroundColor Cyan
                    Write-Host "✅ Địa chỉ kết nối RDP (Ngrok URL): $($tcpTunnel.public_url)" -ForegroundColor Cyan
                    Write-Host "   (Sử dụng địa chỉ này trong Remote Desktop Client)" -ForegroundColor Cyan
                    Write-Host "--------------------------------------------------" -ForegroundColor Cyan
                    exit 0 # Thành công
                } else { Write-Warning "⚠️ Không tìm thấy tunnel TCP từ API lần $attempt." }
            } catch { Write-Warning "❌ Lỗi lấy URL lần $attempt: $_" }
        }
        Write-Error "❌ Không thể lấy URL Ngrok sau $maxAttempts lần thử."
        $ngrokLogPath = Join-Path -Path $env:RUNNER_TEMP -ChildPath "ngrok.log"
        if (Test-Path $ngrokLogPath) { Write-Host "--- Log Ngrok ---"; Get-Content $ngrokLogPath -Tail 10; Write-Host "-----------------" }
        exit 1 # Báo lỗi workflow

    # Bước 7: Giữ cho Workflow chạy
    - name: Giữ cho Workflow hoạt động
      shell: powershell
      run: |
        Write-Host "✅ Máy ảo Windows RDP sẵn sàng! Ngrok đang chạy." -ForegroundColor Green
        Write-Host "   Workflow sẽ tiếp tục chạy để duy trì kết nối."
        while ($true) { Start-Sleep -Seconds 300; Write-Host "$(Get-Date): Workflow vẫn đang chạy..." }
