name: Windows RDP via Ngrok (Direct Token & Specific Password - English Only)

on: workflow_dispatch # Run manually

jobs:
  build:
    runs-on: windows-latest # Run on a Windows VM
    timeout-minutes: 9999 # Keep alive as long as possible (within GitHub limits)

    steps:
    # Step 1: Download Ngrok (Extract directly to current directory)
    - name: Download Ngrok
      shell: powershell
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath . # Ngrok.exe will be in the current directory
        Write-Host "INFO: Ngrok downloaded and extracted."

    # Step 2: Authenticate Ngrok (Using Direct Token - INSECURE!)
    - name: Connect Ngrok Account (Direct Token)
      shell: powershell
      run: |
        # ⚠️ WARNING: Embedding tokens directly is VERY INSECURE.
        $ngrokToken = "2wJOyBLBh4cMau6pWvzMKVgbA3H_gfM4VLsnY57s6GFJ4ztm"
        # Correct path is .\ngrok.exe
        .\ngrok.exe authtoken $ngrokToken
        Write-Host "INFO: Ngrok Authtoken configured directly."

    # Step 3: Enable RDP on Windows
    - name: Enable Remote Desktop (RDP) Access
      shell: powershell
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Write-Host "INFO: RDP enabled and Firewall rule added."

    # Step 4: Create User and Set Password (Simplified version)
    - name: Create RDP User and Set Password
      shell: powershell
      run: |
        $userName = "havpc01"
        $password = "HavpcRDP@2025!" # Requested password
        Write-Host "INFO: Creating/updating user '$userName'..."
        $secPassword = ConvertTo-SecureString $password -AsPlainText -Force
        New-LocalUser -Name $userName -Password $secPassword -FullName "$userName (GitHub Actions)" -Description "Temp RDP User" -ErrorAction SilentlyContinue
        Set-LocalUser -Name $userName -Password $secPassword -ErrorAction SilentlyContinue
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member $userName -ErrorAction SilentlyContinue
        Add-LocalGroupMember -Group "Administrators" -Member $userName -ErrorAction SilentlyContinue
        Write-Host "--------------------------------------------------"
        Write-Host "INFO: RDP user creation/update complete."
        Write-Host "   Username: $userName"
        Write-Host "   Password: $password"
        Write-Host "--------------------------------------------------"

    # Step 5: Start Ngrok Tunnel in Background (Using correct path)
    - name: Create Ngrok Tunnel for RDP (Port 3389)
      shell: powershell
      run: |
        Write-Host "INFO: Starting Ngrok tunnel for port 3389 in background..."
        $ngrokLogPath = Join-Path -Path $env:RUNNER_TEMP -ChildPath "ngrok.log"
        # Correct path is .\ngrok.exe
        Start-Process powershell -ArgumentList "-NoExit", "-Command", "`".\ngrok.exe tcp 3389 --log '$ngrokLogPath'`""
        Write-Host "INFO: Ngrok running in background. Log file at: $ngrokLogPath"

    # Step 6: Get and Display Ngrok URL (Fixed variable parsing)
    - name: Get and Display Ngrok Connection Address
      shell: powershell
      run: |
        $maxAttempts = 5
        $waitTime = 15
        for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
            Write-Host "INFO: Attempt ${attempt}/${maxAttempts}: Waiting ${waitTime} seconds..."
            Start-Sleep -Seconds $waitTime
            Write-Host "INFO: Checking Ngrok process..."
            $ngrokProcess = Get-Process ngrok -ErrorAction SilentlyContinue
            if (-not $ngrokProcess) { Write-Warning "WARN: ngrok.exe process not running!"; continue }
            Write-Host "INFO: Ngrok running (PID: $($ngrokProcess.Id)). Fetching API URL..."
            try {
                $tunnels = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels" -TimeoutSec 10 -ErrorAction Stop
                $tcpTunnel = $tunnels.tunnels | Where-Object {$_.proto -eq 'tcp'} | Select-Object -First 1
                if ($tcpTunnel) {
                    Write-Host "--------------------------------------------------"
                    Write-Host "SUCCESS: RDP Connection Address (Ngrok URL): $($tcpTunnel.public_url)"
                    Write-Host "   (Use this address in your Remote Desktop Client)"
                    Write-Host "--------------------------------------------------"
                    exit 0 # Success
                } else {
                    Write-Warning "WARN: TCP tunnel not found in API response on attempt ${attempt}."
                }
            } catch {
                Write-Warning "WARN: Error fetching URL on attempt ${attempt}: ${_}"
            }
        }
        Write-Error "ERROR: Could not retrieve Ngrok URL after ${maxAttempts} attempts."
        $ngrokLogPath = Join-Path -Path $env:RUNNER_TEMP -ChildPath "ngrok.log"
        if (Test-Path $ngrokLogPath) { Write-Host "--- Ngrok Log ---"; Get-Content $ngrokLogPath -Tail 10; Write-Host "-----------------" }
        exit 1 # Fail workflow

    # Step 7: Keep Workflow Alive
    - name: Keep Workflow Active
      shell: powershell
      run: |
        Write-Host "INFO: Windows RDP VM is ready! Ngrok is running."
        Write-Host "   Workflow will continue running to maintain the connection."
        while ($true) { Start-Sleep -Seconds 300; Write-Host "$(Get-Date): Workflow is still running..." }
